### ISSUE TITLE
Weapon sounds do not seem to be playing at all anymore

### ISSUE THREAD

**Issue by BugmanBugman** [OreCruncher/DynamicSurroundings2#1]
4.0.1.5

**Comment by OreCruncher** [comment]
They do work.  I have been playing in the DireWolf 1.16 pack and they are fine.  Check mobeffects-client.toml to make sure they haven't been turned off.

**Comment by BugmanBugman** [comment]
I found out the cause! It seems to be the performant mod

**Comment by BugmanBugman** [comment]
https://github.com/someaddons/performant_issues/issues/80 reported it there

**Comment by OreCruncher** [comment]
I am play Direwolf20 1.16.4 pack and it has 3.25m version of Performant.  I hear swing sounds and the like.

**Comment by BugmanBugman** [comment]
It’s the 3.26 version that breaks things. It apparently messes around with world tick speed

Sent from my iPhone

On Jan 5, 2021, at 8:38 PM, OreCruncher <notifications@github.com> wrote:

﻿

I am play Direwolf20 1.16.4 pack and it has 3.25m version of Performant. I hear swing sounds and the like.

**Comment by OreCruncher** [comment]
Resolving issue.
