### ISSUE TITLE
Armor sound config

### ISSUE THREAD

**Issue by ChloeDawn** [OreCruncher/DynamicSurroundings2#11]
Currently armor sounds seem to be controlled by the footstep config... But I would like footstep sounds and no armor sounds (as I personally find them rather distracting/overwhelming).

**Comment by OreCruncher** [comment]
Set "Enable Footstep Accents" to false.  (EDIT: The setting is in the Mob Effects settings.)

**Comment by ChloeDawn** [comment]
Ah, thank you! Shame about losing the wet ground effect though

**Comment by OreCruncher** [comment]
Yeah.  I am thinking about reworking that portion of code so that accent providers can be selectively provided.

**Comment by OreCruncher** [comment]
Next update will have more granular options to control accenting.
