### ISSUE TITLE
Biome sounds/ambience do not work correctly in The Twilight Forest.

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [OreCruncher/DynamicSurroundings2#14]
Dynamic Surroundings Version: 4.0.4.1
Twilight Forest Version: 4.0.412
Forge Version: 36.1.4
Minecraft Version: 1.16.5
Latest Log: https://pastebin.com/V2zPkBwy

I've noticed that when testing the twilight forest with dynamic surroundings that the ambience that would normally play when in forest-type biomes doesn't play and instead it plays Cave sounds even when I'm exposed to the sky and there are no blocks above me.

I'm assuming this is because the twilight forest's surface level is lower than the Overworld's and thus dynamic surroundings thinks that I'm in a cave, although that's just my guess as biome sounds don't seem to be working right across the whole dimension.

(Also, I'm unsure if this is the right github for this issue so just let me know and I'd be happy to move this issue to the other repository)

**Comment by OreCruncher** [comment]
Apparently they have yet to fix that issue.  The world is reporting sea level at 64 (same as overworld) though it generates at a lower Y value.  Had this issue back in 1.12.2 as well.

**Comment by The-Bernician-Lamb** [comment]
I see, I'll report it on their github as well then.

Update: It is done: https://github.com/TeamTwilight/twilightforest/issues/1056

**Comment by Tamaized** [comment]
Vanilla issue actually, `World::getSeaLevel` hardcodes the value
```
public int getSeaLevel() {
   return 63;
}
```

Sea level is properly set for our noise settings as well as our chunk provider:
<https://github.com/TeamTwilight/twilightforest/blob/1.16.x/src/generated/resources/data/twilightforest/worldgen/noise_settings/forest_noise_config.json#L4>
and
<https://github.com/TeamTwilight/twilightforest/blob/1.16.x/src/main/java/twilightforest/world/ChunkGeneratorTwilightBase.java#L43>

Not to mention.. the World's method is outright deprecated
![image](https://user-images.githubusercontent.com/9671313/113929442-13668b80-97be-11eb-88c4-6440919db9bb.png)

Another note: I've no idea how you expect the client to even have any of this information to begin with. Servers with custom datapacks can change sea level purely server side.

**Comment by OreCruncher** [comment]
I opened a general "support Twilight Forest" issue in the regular Dynamic Surroundings issue tracker.  Next update will contain config changes for Twlight Forest which will define sea level for the dimension.

**Comment by The-Bernician-Lamb** [comment]
Awesome, Much appreciated!
