### ISSUE TITLE
[Suggestion] Change the culling config buttons to something else

### ISSUE THREAD

**Issue by BugmanBugman** [OreCruncher/DynamicSurroundings2#3]
Lots of players use the combination of ctrl and S a lot, and bringing up the culling menu could cause a lot of player deaths.

**Comment by OreCruncher** [comment]
What's CTRL+S use for?  I havent used it.

**Comment by ChloeDawn** [comment]
Moving backwards whilst holding the sprint keybinding

**Comment by OreCruncher** [comment]
Ah - ok.  Something I don't do. :)  I will see about changing it.

EDIT:  How about CTRL+i?

**Comment by OreCruncher** [comment]
Pushed 4.0.3.5 that changes the keybind to CTRL+i
