### ISSUE TITLE
Tetra Compatability w/ Mob Effects

### ISSUE THREAD

**Issue by anIceyGirl** [OreCruncher/DynamicSurroundings2#4]
Exactly what the title suggests: Native compatibility with the latest version of [Tetra](https://github.com/mickelus/tetra). [(Curseforge Link)](https://www.curseforge.com/minecraft/mc-mods/tetra) 

It's a little bit jarring for me to equip my sword and not play the unsheathing sound, and the same goes for pickaxes, shovels, axes... you get the picture.

**Comment by OreCruncher** [comment]
Dupe of **https://github.com/OreCruncher/DynamicSurroundings/issues/628**
