### ISSUE TITLE
DynamicSurroundings-1.16.4-4.0.3.6 crash on start up

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings2#6]
DynamicSurroundings-1.16.4-4.0.3.6 crash on start up see log
[crash-2021-01-28_19.10.34-fml.txt](https://github.com/OreCruncher/DynamicSurroundings2/files/5890768/crash-2021-01-28_19.10.34-fml.txt)

**Comment by Mysticpasta1** [comment]
https://gist.github.com/Mysticpasta1/5db7cd0b98a2fbdf87c70104b04edebd this was in a modpack I was making

**Comment by Mysticpasta1** [comment]
it is crashing with latest forge for 1.16.5 afaik

**Comment by OreCruncher** [comment]
@Mysticpasta1 See https://github.com/OreCruncher/DynamicSurroundings/issues/659.
@Tsoccerguy3 This is an interesting report.  It's complaining about an invalid location that is valid.  It could be similar to what I see with the other report.

**Comment by OreCruncher** [comment]
Pushed 4.0.3.7 to CurseForge to work around JavaScript issue w/Forge 36 running w/Java 8.
