### ISSUE TITLE
DynamicSurroundings-1.16.4-4.0.3.7 breaks most of the features

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings2#7]
particle effects , Aurora , sound etc,,.. are not working or not working in full . Multiplayer most features are not working . single player some are not working . Looks like everything that broke is using default vanilla

**Comment by OreCruncher** [comment]
Its working for me in my DW20 pack.  What pack are you using?  Also, can you link your latest.log?  There may be an error in there that prevents processing of configurations during client connect.  Speaking of - is this a single player world or are you connecting to a server?

**Comment by Tsoccerguy3** [comment]
This is in Multiplayer . on a paper 1.16.5 server , testing the mod by itself , in a snowy taiga biome no breath , aurora , etc . I tested with and without the server texture pack with the same results . It may be a Java problem , Paper is starting to move to java 11 or higher . some mods are java 8 and higher . Java 16 is so much more advanced . 

![2021-01-29_16 31 37](https://user-images.githubusercontent.com/22108822/106329818-2013b400-6250-11eb-8a1e-778326d927be.png)
![2021-01-29_16 31 42](https://user-images.githubusercontent.com/22108822/106329821-20ac4a80-6250-11eb-8dd8-cc33defbebaf.png)



[debug.log](https://github.com/OreCruncher/DynamicSurroundings2/files/5896418/debug.log)

**Comment by Tsoccerguy3** [comment]
things seemed to be working on 4.0.3.5

**Comment by OreCruncher** [comment]
Ah - Paper.  This is the second report.  Paper is basically vanilla no mods right?

**Comment by Tsoccerguy3** [comment]
https://github.com/PaperMC

Its a fork of spigot , tries to be more optimized , it uses the same plugins that bukkit , spigot uses

**Comment by OreCruncher** [comment]
Try this JAR: https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.3.8

**Comment by Tsoccerguy3** [comment]
4.0.3.8 appears to be working on Multiplayer now

**Comment by Tsoccerguy3** [comment]
this update works

**Comment by OreCruncher** [comment]
OK.  When Forge connects to a Forge server it will get two events for tag updates.  When connecting to Paper it gets one.  Explains some things.

**Comment by OreCruncher** [comment]
@Tsoccerguy3 Can you do me a favor and test out this jar?  I would also like to get a copy of the latest.log from when you log in.  (I am changing how connections are detected.)  https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.3.9

**Comment by Tsoccerguy3** [comment]
i tested in single and multi player seems to work , 
[debug.log](https://github.com/OreCruncher/DynamicSurroundings2/files/5922611/debug.log)

**Comment by Tsoccerguy3** [comment]
I tested and compiled today's build and it is working. A
small mistake in the build.gradle, that throws a error stopping the compile
maven { url = 'http://repo.spongepowered.org/maven' }
change to this
maven { url = 'https://repo.spongepowered.org/maven' }

**Comment by OreCruncher** [comment]
Yes.  They changed the repo access to https recently.  I haven't pushed my current build.gradle yet.

**Comment by Tsoccerguy3** [comment]
This may or may not be bugs , i could not find a way to fix lightning sound when lighting strikes close 
to you, the sound is muffled and stops suddenly . Easy to test by trigger lightning to hit a block in front of you . Also i could not find a way to set the aurora in a biome . Is it hard coded to colder biomes ?

**Comment by OreCruncher** [comment]
I haven't experienced muffling of lightening.  I will take a look to make sure I didn't break anything.  And there is a way to set auroras for a biome.  For resource packs checkout this issue (https://github.com/OreCruncher/DynamicSurroundings/issues/650).  It's specific to dimensions.json, but you can put in a biomes.json as well.

For example, if you want to turn on aurora for all biomes you could create a biomes.json and put the following in it.  (I do this for testing on my dev box):
```
[
  {
    "conditions": "true",
    "_comment": "Display aurora",
    "aurora": true
  }
]
```
If you want to set this without putting it in a resource pack you can drop it into the .minecraft/config/dsurround/configs/dsurround folder. (You may need to create that path.) Make sure you drop it specifically into this path.

**Comment by OreCruncher** [comment]
The lightning issue appears to be related to occlusion.  There will be an option in the next update that has a config option to enable/disable occlusion of the WEATHER sound category, and by default it will be turned  off.
